CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Firstname] NVARCHAR(150) NOT NULL,
	[Lastname] NVARCHAR(150) NOT NULL,
	[Email] NVARCHAR(150) NOT NULL,
	[Username] NVARCHAR(150) NOT NULL,
	[Password] NVARCHAR(150) NOT NULL,
	[UserRole] NVARCHAR(150) NOT NULL,
	CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id]),
)
